import { AnalysisResult } from '../types';
import { logger } from '../utils/logger';

/**
 * Generate a simple text-based analysis report.
 * Returns a string suitable for download as .txt or conversion to PDF.
 */
export class ReportService {
  static generateReport(result: AnalysisResult): string {
    const divider = '═'.repeat(60);
    const thinDivider = '─'.repeat(60);

    const lines = [
      divider,
      '  SATQUERY AI — ANALYSIS REPORT',
      divider,
      '',
      `Date: ${result.createdAt.toISOString()}`,
      `Report ID: ${result.id}`,
      '',
      thinDivider,
      '  QUERY',
      thinDivider,
      result.query,
      '',
      thinDivider,
      '  INPUT INFORMATION',
      thinDivider,
      `Input Type: ${result.inputType}`,
      `Detected Task: ${result.detectedTask}`,
      '',
      thinDivider,
      '  MODELS USED',
      thinDivider,
      `Primary Model: ${result.modelUsed}`,
      `Model Source: ${result.modelSource}`,
      `Tools Used: ${result.toolsUsed.join(', ') || 'None'}`,
      '',
      thinDivider,
      '  AI RESPONSE',
      thinDivider,
      result.answer,
      '',
      thinDivider,
      '  CONFIDENCE',
      thinDivider,
      `${(result.confidence * 100).toFixed(1)}%`,
      '',
      thinDivider,
      '  EXECUTION SUMMARY',
      thinDivider,
      `Processing Time: ${result.processingTime}ms`,
      '',
      ...result.executionTrace.map(
        (step) => `  ${step.status === 'completed' ? '✓' : step.status === 'failed' ? '✗' : '○'} ${step.name}${step.detail ? ` — ${step.detail}` : ''}`
      ),
      '',
      divider,
      '  Generated by SatQuery AI',
      divider,
    ];

    return lines.join('\n');
  }
}
